### ISSUE TITLE
añadir DRF al proyecto 

### ISSUE THREAD

**Issue by caherdenez** [PyBAQ/vanzare#8]
https://www.django-rest-framework.org/
ademas se debe soportar `jwt` 
https://github.com/GetBlimp/django-rest-framework-jwt

**Comment by Scot3004** [comment]
Y se creara un front aparte o como tienes prevista la parte visual?

**Comment by Cesar0510** [comment]
@Scot3004  la idea del fron aparte no es clara aun, poner el DRF es para tener mas flexibilidad.
